version: "2.3"
services:
  mysql:
    image: mysql:5.6
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=todo
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=laravel
      - MYSQL_PASSWORD=laravel
    healthcheck:
      test: [
        "CMD-SHELL",
        "mysql --connect-timeout=1 -u root -ppassword -e \"select 1;\" > /dev/null 2>&1 || exit 1"
      ]
      interval: 5s
      timeout: 5s
      retries: 3
  app:
    build: .
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=todo
      - DB_USERNAME=laravel
      - DB_PASSWORD=laravel
    ports:
      - 8090:80
    links:
      - mysql
    depends_on:
      mysql:
        condition: service_healthy

