// flow-typed signature: 6fc68f2fe9f115357f6d0d3e79e47c83
// flow-typed version: <<STUB>>/rc-queue-anim_v^1.4.1/flow_v0.65.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'rc-queue-anim'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'rc-queue-anim' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'rc-queue-anim/dist/rc-queue-anim' {
  declare module.exports: any;
}

declare module 'rc-queue-anim/dist/rc-queue-anim.min' {
  declare module.exports: any;
}

declare module 'rc-queue-anim/es/animTypes' {
  declare module.exports: any;
}

declare module 'rc-queue-anim/es/index' {
  declare module.exports: any;
}

declare module 'rc-queue-anim/es/QueueAnim' {
  declare module.exports: any;
}

declare module 'rc-queue-anim/es/utils' {
  declare module.exports: any;
}

declare module 'rc-queue-anim/lib/animTypes' {
  declare module.exports: any;
}

declare module 'rc-queue-anim/lib/index' {
  declare module.exports: any;
}

declare module 'rc-queue-anim/lib/QueueAnim' {
  declare module.exports: any;
}

declare module 'rc-queue-anim/lib/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'rc-queue-anim/dist/rc-queue-anim.js' {
  declare module.exports: $Exports<'rc-queue-anim/dist/rc-queue-anim'>;
}
declare module 'rc-queue-anim/dist/rc-queue-anim.min.js' {
  declare module.exports: $Exports<'rc-queue-anim/dist/rc-queue-anim.min'>;
}
declare module 'rc-queue-anim/es/animTypes.js' {
  declare module.exports: $Exports<'rc-queue-anim/es/animTypes'>;
}
declare module 'rc-queue-anim/es/index.js' {
  declare module.exports: $Exports<'rc-queue-anim/es/index'>;
}
declare module 'rc-queue-anim/es/QueueAnim.js' {
  declare module.exports: $Exports<'rc-queue-anim/es/QueueAnim'>;
}
declare module 'rc-queue-anim/es/utils.js' {
  declare module.exports: $Exports<'rc-queue-anim/es/utils'>;
}
declare module 'rc-queue-anim/lib/animTypes.js' {
  declare module.exports: $Exports<'rc-queue-anim/lib/animTypes'>;
}
declare module 'rc-queue-anim/lib/index.js' {
  declare module.exports: $Exports<'rc-queue-anim/lib/index'>;
}
declare module 'rc-queue-anim/lib/QueueAnim.js' {
  declare module.exports: $Exports<'rc-queue-anim/lib/QueueAnim'>;
}
declare module 'rc-queue-anim/lib/utils.js' {
  declare module.exports: $Exports<'rc-queue-anim/lib/utils'>;
}
